# Generated by Django 2.2 on 2019-05-04 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('timestamp', 'title', 'pk')},
        ),
    ]
